[package]
name = "vowel-counter"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.85"

[dependencies.web-sys]
version = "0.3"
features = [
]

